"""Public API for the D&D Assistant local AI bridge."""

from .agent import (
    AgentError,
    AgentLimitError,
    AgentLimits,
    AgentResult,
    AgentRuntime,
    EmptyFinalResponseError,
    IterationLimitError,
    ToolCallLimitError,
    ToolNotAllowedError,
    ToolTransportFailureError,
    UnknownToolError,
    serialize_tool_result,
)
from .config import AgentSettings, BridgeSettings, OllamaSettings, ServerSettings
from .errors import (
    BridgeError,
    OllamaConnectionError,
    OllamaError,
    OllamaHTTPStatusError,
    OllamaProtocolError,
    OllamaTimeoutError,
    OllamaTransportError,
    OneCAuthenticationError,
    OneCProtocolError,
    OneCTransportError,
)
from .models import (
    ChatMessage,
    ChatRole,
    HealthResponse,
    ModelRequest,
    ModelResponse,
    ModelPerformanceMetrics,
    ModelStreamChunk,
    ModelToolCall,
    ModelUsageMetrics,
    ToolDefinition,
    ToolDescriptor,
    ToolError,
    ToolResult,
)
from .onec_client import OneCClient
from .ollama_client import OllamaClient
from .ollama_provider import OllamaGenerationSettings, OllamaProvider
from .ollama_tools import to_ollama_tools
from .provider import ModelProvider
from .service import AssistantService
from .tool_registry import ToolRegistry

__all__ = [
    "AgentError",
    "AgentLimitError",
    "AgentLimits",
    "AgentResult",
    "AgentRuntime",
    "AgentSettings",
    "AssistantService",
    "BridgeError",
    "BridgeSettings",
    "ChatMessage",
    "ChatRole",
    "EmptyFinalResponseError",
    "HealthResponse",
    "IterationLimitError",
    "ModelProvider",
    "ModelPerformanceMetrics",
    "ModelRequest",
    "ModelResponse",
    "ModelStreamChunk",
    "ModelToolCall",
    "ModelUsageMetrics",
    "OllamaClient",
    "OllamaConnectionError",
    "OllamaError",
    "OllamaHTTPStatusError",
    "OllamaGenerationSettings",
    "OllamaProtocolError",
    "OllamaProvider",
    "OllamaSettings",
    "OllamaTimeoutError",
    "OllamaTransportError",
    "OneCAuthenticationError",
    "OneCClient",
    "OneCProtocolError",
    "OneCTransportError",
    "ServerSettings",
    "ToolDefinition",
    "ToolCallLimitError",
    "ToolDescriptor",
    "ToolError",
    "ToolNotAllowedError",
    "ToolRegistry",
    "ToolResult",
    "ToolTransportFailureError",
    "UnknownToolError",
    "serialize_tool_result",
    "to_ollama_tools",
]
